sudo: required
services:
  -docker

before_install:
  - docker build -t nicomdt/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

  after_success:
  - docker build -t nicomdt/multi-client ./client
  - docker build -t nicomdt/multi-nginx ./nginx
  - docker build -t nicomdt/multi-server ./server
  - docker build -t nicomdt/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nicomdt/multi-client
  - docker push nicomdt/multi-nginx
  - docker push nicomdt/multi-server
  - docker push nicomdt/multi-worker

